package com.chendev.ticketflow.order.dto;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;

@Getter
public class CreateOrderRequest {

    @NotNull(message = "Ticket type ID is required")
    private Long ticketTypeId;

    @NotNull(message = "Quantity is required")
    @Min(value = 1, message = "Quantity must be at least 1")
    @Max(value = 4, message = "Maximum 4 tickets per order")
    private Integer quantity;

    // Idempotency key generated by frontend — UUID recommended
    // Same key = same request, prevents duplicate orders on retry
    @NotBlank(message = "Request ID is required for idempotency")
    private String requestId;
}